### ISSUE TITLE
wrong file type message reconnecting datasource with datasources table

### ISSUE THREAD

**Issue by enricofer** [enricofer/changeDataSource#1]
Baswein regenerativedesigngroup.com
Thanks! I installed it. I experimented a little with a shape file by moving the shape file and all it’s associated fils to a subfolder. It moved the layer to the unhandled layer (great). When I reconnected the file with the global toolbar icon it told me that my shape file was the wrong file type. When I reconnected using the right click method it reconnected fine. I did lose my styles that I had set up for the layer is that normal? Thanks for doing all of this!

**Comment by baswein** [comment]
Still getting the wrong file type error with the right click layer dialog- see screen shot. But then the layer loads fine. 
![file type error](https://cloud.githubusercontent.com/assets/15817745/11138717/c333a618-8993-11e5-8101-0dd9583d88c4.JPG)

When I go through the global It works well if the file path is different. If it is the same it won't reload it. (stays grey) For testing purposes I put a number of layers on a flash drive that I can remove. When I put the flash drive back in I can't tell it to reconnect with the same layer again. Draftsight has a refresh button that does the trick. As does indesign and Autocad. 
![draftsight missing link](https://cloud.githubusercontent.com/assets/15817745/11138948/1e710388-8997-11e5-9814-1ae15e350e96.JPG)

Also if I cancel I get this python error:
Traceback (most recent call last):
  File "C:/Users/A/.qgis2/python/plugins\changeDataSource-master\changeDataSource.py", line 401, in 
    edit.clicked.connect(lambda: self.browseDS(row))
  File "C:/Users/A/.qgis2/python/plugins\changeDataSource-master\changeDataSource.py", line 405, in browseDS
    newType,newProvider,newDatasource = dataSourceBrowser.uri()
ValueError: need more than 2 values to unpack
FYI
I'm running 2.8.3 on win 7 64bit. 
Thanks for all this! I have also been enjoying your street view plugin.

**Comment by enricofer** [comment]
Ok. Almost everything should be now fixed. https://github.com/enricofer/changeDataSource/commit/13aa396d417776162041d37f02130219ae0702ae
About refreshing reconnectable layer, I inserted a button "reconcile unhandled" that appears on the left under layers list. It allows to massively reconcile layer when datasources return available.
Item in layers list are now ordered as from legend.
Download from master version to install.
Thanks for your accurate reports

**Comment by baswein** [comment]
The Reconcile all unhandled llayers works great. Unless I reconcile a single layer first either through the right click method or the Global method Then when I click the ChangeDataSourse button I get this error:

Traceback (most recent call last):
  File "C:/Users/A/.qgis2/python/plugins\changeDataSource-master\changeDataSource.py", line 551, in run
    self.populateLayerTable()
  File "C:/Users/A/.qgis2/python/plugins\changeDataSource-master\changeDataSource.py", line 390, in populateLayerTable
    layer = self.badLayersHandler.getUnhandledLayerFromBadId(lid)
  File "C:/Users/A/.qgis2/python/plugins\changeDataSource-master\changeDataSource.py", line 633, in getUnhandledLayerFromBadId
    return QgsMapLayerRegistry.instance().mapLayer( self.getUnhandledLayers()[badId]["tempid"] )
KeyError: u'soi_hhea20151112174614485'

Also in the global method I can only reconcile the bottom layer in the picture. The others I reconciled with the reconciled unhandled button. 
![connected reconnected files](https://cloud.githubusercontent.com/assets/15817745/11164284/d7322dd4-8ab9-11e5-9761-efe656aee78b.JPG)

When I start the unhandled layers- new england poly and soils shape files ask for a crs. 

Thanks again.

**Comment by baswein** [comment]
The Reconcile all unhandled llayers works great. Unless I reconcile a single layer first either through the right click method or the Global method Then when I click the ChangeDataSourse button I get this error:

Traceback (most recent call last):
  File "C:/Users/A/.qgis2/python/plugins\changeDataSource-master\changeDataSource.py", line 551, in run
    self.populateLayerTable()
  File "C:/Users/A/.qgis2/python/plugins\changeDataSource-master\changeDataSource.py", line 390, in populateLayerTable
    layer = self.badLayersHandler.getUnhandledLayerFromBadId(lid)
  File "C:/Users/A/.qgis2/python/plugins\changeDataSource-master\changeDataSource.py", line 633, in getUnhandledLayerFromBadId
    return QgsMapLayerRegistry.instance().mapLayer( self.getUnhandledLayers()[badId]["tempid"] )
KeyError: u'soi_hhea20151112174614485'

Also in the global method I can only reconcile the bottom layer in the picture. The others I reconciled with the reconciled unhandled button. 
![connected reconnected files](https://cloud.githubusercontent.com/assets/15817745/11164284/d7322dd4-8ab9-11e5-9761-efe656aee78b.JPG)

When I start the unhandled layers- new england poly and soils shape files ask for a crs. 

Thanks again.

**Comment by enricofer** [comment]
I was trying to preserve original layer order but I found that there are too many situations to manage: partial reconciling, reconciling after adding new layers etc... so I rollback to actual layer order: https://github.com/enricofer/changeDataSource/commit/72a1b22d4ba30d228eb948df1357d07584bda4fa
I want to thank you for your accurate support and issue checking! Really unvaluable! Thanks!
If you don't find any other issue I would release new version and publish it to the repository.

Regards.
Enrico Ferreguti

PS Would you like to test the upcoming new version of go2streetview? https://github.com/enricofer/go2streetview/archive/master.zip

**Comment by baswein** [comment]
My flash drive was assigned a new drive letter so it is a little different than before but I keep getting these errors. 
When I try to re-associate a file:

An error has occured while executing Python code:
Traceback (most recent call last):
  File "C:/Users/A/.qgis2/python/plugins\changeDataSource-master\setdatasource.py", line 130, in changeDataSourceAction
    self.applyDataSource(self.layer,self.selectDatasourceCombo.currentText().lower().replace(' ',''),self.lineEdit.toPlainText())
  File "C:/Users/A/.qgis2/python/plugins\changeDataSource-master\setdatasource.py", line 159, in applyDataSource
    applyLayer.setDataSource(newDatasource,applyLayer.name(),newProvider)
AttributeError: 'QgsVectorLayer' object has no attribute 'setDataSource'

Or This one when I try to to do the global reconnect:
An error has occured while executing Python code:
Traceback (most recent call last):
  File "C:/Users/A/.qgis2/python/plugins\changeDataSource-master\changeDataSource.py", line 549, in buttonBoxHub
    QgsMapLayerRegistry.instance().removeMapLayer(self.layersPropLayer.id())
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted

And this one when I Use reconcile all: 
An error has occured while executing Python code:
Traceback (most recent call last):
  File "C:/Users/A/.qgis2/python/plugins\changeDataSource-master\changeDataSource.py", line 558, in reconcileUnhandled
    self.applyDSChanges(reconcileUnhandled = True)
  File "C:/Users/A/.qgis2/python/plugins\changeDataSource-master\changeDataSource.py", line 537, in applyDSChanges
    if self.changeDSTool.applyDataSource(rowLayer,rowProvider,rowDatasource):
  File "C:/Users/A/.qgis2/python/plugins\changeDataSource-master\setdatasource.py", line 159, in applyDataSource
    applyLayer.setDataSource(newDatasource,applyLayer.name(),newProvider)
AttributeError: 'QgsVectorLayer' object has no attribute 'setDataSource'

 Thanks as always. I'm looking forward to checking out the go2Streetview. 
-Bas

**Comment by enricofer** [comment]
I can't replicate the last error.
Do you get it even after qgis restart?

**Comment by baswein** [comment]
Yes- Although This one looks slightly different here are my steps: 
Open QGIS --> Open Recent project --> Computer beeps and managing bad layers window pops up and my pointer turns to an hourglass--> I click the open plugin table button (same error if I wait to open the global change data source)--> I do a find "F:" and replace "J:" click replace --> all the layers turn yellow--> I click apply --> error code

Traceback (most recent call last):
  File "C:/Users/A/.qgis2/python/plugins\changeDataSource-master\changeDataSource.py", line 553, in buttonBoxHub
    self.applyDSChanges()
  File "C:/Users/A/.qgis2/python/plugins\changeDataSource-master\changeDataSource.py", line 537, in applyDSChanges
    if self.changeDSTool.applyDataSource(rowLayer,rowProvider,rowDatasource):
  File "C:/Users/A/.qgis2/python/plugins\changeDataSource-master\setdatasource.py", line 159, in applyDataSource
    applyLayer.setDataSource(newDatasource,applyLayer.name(),newProvider)
AttributeError: 'QgsVectorLayer' object has no attribute 'setDataSource'

**Comment by enricofer** [comment]
The problem was the 2.8.3 version. I was making use of a more recent method....
Now fixed: https://github.com/enricofer/changeDataSource/commit/3554c9102e57c72e4a9e5cbfb7a9100dca9b3f59

**Comment by enricofer** [comment]
I push a new commit to fix a bug https://github.com/enricofer/changeDataSource/commit/deb28222c92ed4d5ffae2704326731b413314a0b
Please note that I implemented a checkbox in plugin dialog called "handle bad layers" to enable/disable the feature. Furthermore you will find a new expression field to calculate datasources strings from layers properties.

**Comment by baswein** [comment]
Enrico,
Your handle bad layers window is not starting up when I open the project. 
I get the normal one. 
I tried unchecking/restarting and checking/restarting the handle bad layers check box. (nice feature) It didn't help. Sorry to throw you off using 2.8.3 but I'm trying to get people in my office using QGIS and I know they won't keep installing every 3 months. 
-Bas

**Comment by enricofer** [comment]
Hi Bas,
The last commits fix exactly the issue you reported. Did you download the last master version?
Don't mind about release, the plugin should be compatible with every release > 2.4.
Regatds

----- Messaggio originale -----
Da: "baswein" notifications@github.com
Inviato: ‎23/‎11/‎2015 14:54
A: "enricofer/changeDataSource" changeDataSource@noreply.github.com
Cc: "enrico ferreguti" enricofer@gmail.com
Oggetto: Re: [changeDataSource] wrong file type message reconnectingdatasource with datasources table (#1)

Enrico,
Your handle bad layers window is not starting up when I open the project. 
I get the normal one. 
I tried unchecking/restarting and checking/restarting the handle bad layers check box. (nice feature) It didn't help. Sorry to throw you off using 2.8.3 but I'm trying to get people in my office using QGIS and I know they won't keep installing every 3 months. 
-Bas

**Comment by baswein** [comment]
I had the right master. I just had to unload it and reload it in the plugins dialog. 
Worked great.

**Comment by enricofer** [comment]
Hi Bas,
I finally publish the plugin:
https://geogear.wordpress.com/2016/01/29/changedatasourceplugin-plugin-release-2-0/
Feel free to correct my bad english!
Thank you for your suggestions.

Enrico Ferreguti

2015-11-23 22:47 GMT+01:00 baswein notifications@github.com:
