### ISSUE TITLE
update to QGis3

### ISSUE THREAD

**Issue by bipo76** [enricofer/changeDataSource#10]
Is there an update to QGis 3.x.x planned?
Thanks

**Comment by enricofer** [comment]
Have a look to this comments thread https://geogear.wordpress.com/2016/01/29/changedatasourceplugin-plugin-release-2-0/#comments

**Comment by bipo76** [comment]
Thanks for your quick reply !
Kind regards
Philipp

Von: enrico ferreguti <notifications@github.com>
Gesendet: Dienstag, 1. Mai 2018 21:42
An: enricofer/changeDataSource <changeDataSource@noreply.github.com>
Cc: Philipp Jörg <joerg@tur.ch>; Author <author@noreply.github.com>
Betreff: Re: [enricofer/changeDataSource] update to QGis3 (#10)


Have a look to this comments thread https://geogear.wordpress.com/2016/01/29/changedatasourceplugin-plugin-release-2-0/#comments

**Comment by Vitruvius21** [comment]
There is a Pull Request about this. ► https://github.com/enricofer/changeDataSource/pull/11

**Comment by enricofer** [comment]
I merged the @ChrFr PR and extended migration to datasources table. 
I excluded bad layers handling that need a rewrite.
prease check and test it: https://github.com/enricofer/changeDataSource/tree/qgis3-migration-test

@pcav @ghtmtt @dpsspatial Anyway, just for information, I'm going to submit a QEP for core integration of plugin features. (at least for his basic functionality)

**Comment by dpsspatial** [comment]
This passes our workflow test on Windows and Linux Mint. Thank you very much for making this upgrade, and crossing fingers this makes its way into core QGIS, and if there is a funding need for this, please get in touch. Thanks again!

**Comment by enricofer** [comment]
published on repository: http://plugins.qgis.org/plugins/changeDataSource/version/3.0/
for your information I report this thread: http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Handle-Bad-Layers-td5377012.html#a5377121
and this feature request: https://issues.qgis.org/issues/19790

**Comment by dpsspatial** [comment]
Thank you again, everyone! Great tool, and definitely worth adding to core.
