### ISSUE TITLE
export souce table

### ISSUE THREAD

**Issue by FERRATON** [enricofer/changeDataSource#4]
it would be very nice to add an export function of the source table by copy / paste or to a spreadsheet

**Comment by enricofer** [comment]
I'm not sure I understand the question:
copy / paste from attribute table and a spreadsheet is always possible. 
I can't figure what is the added value to do this from the plugin.

**Comment by FERRATON** [comment]
sorry for my bad English...

this new feature is not directly useful to change sources. But users ask me to export the same table as the one that appears in the plugin dialog box ( layer name , type, data source) .
Useful for managing the sources for an administrator.

**Comment by enricofer** [comment]
If you need to export layers details as a spreadsheet I suggest you to give a try to Layer Board plugin that provide such feature in cvs format. http://plugins.qgis.org/plugins/LayerBoard/

**Comment by FERRATON** [comment]
OK... thanks

**Comment by AlisterH** [comment]
Hi, would you consider merging a pull request for this feature if it was proposed?  

Often it is useful just to make a list of all the layers in a project, with their data sources.  I can do this by running some code in the Python console and selecting the output to copy and paste.  Your plugin provides a ready made table of this information, so it seems like it would be a perfect place to add an export or copy/paste ability.  The layerboard plugin is a lot more complicated.

Thanks for the great plugin.

**Comment by czalaviek** [comment]
I'm voting for it. I've seen similar functions in other plugins, but it's hard to find them after installation. I bring You my YES.
Marcin (nick: czalaviek)

Dnia 1 października 2019 03:03:24 CEST, AlisterH <notifications@github.com> napisał(a):
>Hi, would you consider merging a pull request for this feature if it
>was proposed?  
>
>Often it is useful just to make a list of all the layers in a project,
>with their data sources.  I can do this by running some code in the
>Python console and selecting the output to copy and paste.  Your plugin
>provides a ready made table of this information, so it seems like it
>would be a perfect place to add an export or copy/paste ability.  The
>layerboard plugin is a lot more complicated.
>
>Thanks for the great plugin.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/enricofer/changeDataSource/issues/4#issuecomment-536813391

-- Wysłane za pomocą K-9 Mail.

**Comment by enricofer** [comment]
Your contribution is welcome. Ask if you need any help.

**Comment by AlisterH** [comment]
I realised that changedatasource creates a layer with all of the information, and on QGIS 2.x the QuickExport plugin allows me to export it easily.
So rather than adding features to changedatasource I thought it was better to port QuickExport  to QGIS 3.x.
See https://github.com/3liz/QgisQuickExportPlugin/pull/14

**Comment by AlisterH** [comment]
To clarify, that last link was a pull request, not a ticket.  I got it working in QGIS3, and upstream said they will take it over, although they haven't got around to making a release yet...

Of course, once you've noticed the layerTable layer, you can just select all the features from the layerTable layer and copy them.
