### ISSUE TITLE
layer properties and joins break when layer re-sourced with changeDataSource

### ISSUE THREAD

**Issue by rjwillson** [enricofer/changeDataSource#5]
I think this issue started after I upgraded to QGIS 2.14. 

what happens is that after re-sourcing a layer, the layer's style, virtual fields, joins, etc are lost. This happens whether one uses any of the 3 ways of re-sourcing through the plugin (that is (1) right clicking a single layer and selecting "change vector datasource", (2) changing multiple layers by using the panel, and (3) by using the "handle bad layers" feature

I'm pretty sure this didn't happen previously as I set up my company's workflow to use this great plugin to change datasources for many layers at once, and then when I went to run a demo 2 weeks ago the the layer properties were lost after re-sourcing.

I confirmed that re-sourcing bad layers using QGIS's built in procedure when one opens a project will retain all of my layer property settings and I also confirmed that the Picklayers plugin's "change data source" also still retains the layer property settings. However, these are less efficient ways to change the data sources because the "changeDataSource" plugin has some great features and one can change multiple sources at once. Plus it has the broken layers enhancement upon startup

any chance this could be fixed soon?

**Comment by enricofer** [comment]
Thanks, I wasn't aware of the issue.
For now I have done a quick fix, that perhaps could bring in some case to crash.
Download it from master: https://github.com/enricofer/changeDataSource/archive/master.zip
Please check and send me feedback.

**Comment by rjwillson** [comment]
the quick fix totally worked as I tested it by right clicking a single layer and selecting "change vector datasource", as well as by changing multiple layers using the panel. Both methods worked as the layer's virtual fields, styles, and joins were retained or kept intact 

thanks so much!

I tried to see if it worked with the handle bad layers extended functionality as well but I think it may have been disabled in the quick fix as I couldn't seem to trigger it
