### ISSUE TITLE
Showing passwords in database connection strings

### ISSUE THREAD

**Issue by dpsspatial** [enricofer/changeDataSource#6]
Would it be possible to change the password output in the URI for PostgreSQL, MSSQL, etc. to ****\* rather than the actual password?

**Comment by enricofer** [comment]
Do you mean new (from 2.14) authentication mananagement support (under option menu) or simply password masking to preserve privacy?
Anyway I would schedule this to the qgis 3.0/python 3/qt5 migration.

**Comment by dpsspatial** [comment]
I think masking would be enough... if QGIS 3.0 is it, then I'll close this thread. Thanks for your work on this plugin, we use it a lot to refresh PostGIS/MSSQL layers when we've added new columns from tables we create in SQL... among other things!
