### ISSUE TITLE
Handle Bad layers not working.

### ISSUE THREAD

**Issue by baswein** [enricofer/changeDataSource#8]
Enrico- thanks for the plugin - the handle bad layers does not seem to be taking over for me anymore. See my this thread. https://gis.stackexchange.com/questions/200138/how-to-ignore-handle-bad-layers-in-qgis/242422?noredirect=1#comment379793_242422

**Comment by enricofer** [comment]
Hi Baswein, I admit there are some uncaught situations throwing errors and exceptions, but the basic unhandled Layers managing goes well here under win10 and qgis 2.18.6. About this, I just cleaned the code to prevent some exceptions so I recommend you to download and install the new master version before retrying.
Could you help me to replicate the reported issue step by step?

**Comment by enricofer** [comment]
Any Thoughts?

**Comment by baswein** [comment]
Thanks for the bump. It seems to be working again on QGIS 2.18.7. I haven't changed anything I am aware of other than restarting my computer. I'll keep an eye on it and if it breaks again I'll see if I can isolate it. Thanks again.

**Comment by baswein** [comment]
Enrico - Today I noticed that the handle bad layers doesn't work if I open my project by double clicking on the .qgs file rather than opening QGIS first. That might have been the issue I encountered before.

**Comment by enricofer** [comment]
Apparently QGIS handle project files in different ways... but this is truly beyond the plugin scope... We should open a core ticket on a something that is already in QGIS3... Did you noticed that in QGIS3 unhandled layers remain in legend?

**Comment by baswein** [comment]
I am fine with having to open QGIS first. I haven't played around with QGIS3 but it would be great if they remained in the legend natively.
