### ISSUE TITLE
Changing data source does not update the extent of rasters

### ISSUE THREAD

**Issue by Dan-Knott** [enricofer/changeDataSource#9]
I am using changeDataSource to change a collection of layers in a QGIS workspace, to investigate a new domain.  While the tool works perfectly for vector files, I've found that raster layers don't display at all. I've worked out that this is due to the layers extent meta data not being updated. The metadata can be removed from the .qgs file with a text editor, and then the layers display correctly.

Would it be possible to trigger an update of this metadata when changing the raster data source?

**Comment by enricofer** [comment]
issue fixed: https://github.com/enricofer/changeDataSource/commit/ac03e673cedc90876fd6f5604909beab2c8eb066
Thanks for submission.
